# Generated by Django 5.2.10 on 2026-01-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='max_score',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attemptanswer',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='attempt',
            name='finished_reason',
            field=models.CharField(choices=[('completed', 'Completed'), ('timeout', 'Timeout')], default='completed', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
