# Generated by Django 5.2.10 on 2026-01-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_max_score_attempt_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_reason',
            field=models.CharField(choices=[('completed', 'Completed'), ('timeout', 'Timeout')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.test'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
